add 'View Bookmarks' to default channel
wbond/package_control_channel pull request #7997
Opened 2020-07-27 06:04 UTC by adam-zethraeus

This package provides access to a view of all bookmarks in your window in the most sublime-defaulty-way possible.
* It adds a menu item that nests in 'Bookmarks'.
* It adds a command pallet item that lists with 'Bookmarks'.

2020-08-26 22:28 UTC, adam-zethraeus commented
giving it a shot! https://github.com/ibensw/LsBookmarks/pull/3

2020-09-21 18:11 UTC, FichteFoll commented
I suggest you replace the existing unmaintained package instead of adding a fork to the list that users need to go through. You can either remove ViewBookmarks and exchange the urls of LsBookmarks or remove LsBookmarks and add a `previous_names` array with the old name to trigger a rename.

2020-12-19 15:54 UTC, braver requested changes
Sorry this has sat unattended for a while. We're very close to merging this, just the final bit of housekeeping.

2020-12-19 15:54 UTC, braver commented on repository/v.json
> +			"readme": "https://raw.githubusercontent.com/adam-zethraeus/SublimeViewBookmarks/master/README.md",
Since your "details" point to a GitHub repo, you shouldn't add the "issues" and "readme" keys if these things are just in their normal place.

2020-12-20 02:19 UTC, adam-zethraeus commented
@braver hope that'll do it!

2020-12-23 12:16 UTC, braver commented
Thanks! Two final things to do in your [repo](https://github.com/adam-zethraeus/SublimeViewBookmarks) though:

- Please [add a license](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository). If you're not sure what kind to pick, MIT is a good one for general purpose open source stuff.
- We require [semver](https://semver.org) version numbers with 3 numbers, e.g. `1.0.0` instead of just `1.0`. Please tag a new release with a compatible version number.

2020-12-23 18:39 UTC, adam-zethraeus commented
Oops. don't know how the non-semver got in there.
Both things fixed now!

2020-12-23 18:41 UTC, adam-zethraeus commented
@braver No more warnings :)

2020-12-23 19:17 UTC, braver commented
> - All checks passed

🎉

2020-12-23 19:18 UTC, merged