Added DarkDonut-Strawberry Color Scheme
wbond/package_control_channel pull request #8044
Opened 2020-09-16 06:13 UTC by dakshamdev

Here is your Strawberry Flavoured DarkDonut Color Scheme for one of our favorite Text Editors ::::::    SUBLIME TEXT!!!
🍓🍓🍓 For Strawberry Lovers!
Easy one eyes.
Enjoy!!!! 🎃

2020-09-16 08:19 UTC, rwols commented
In your color scheme, you have

```
        "line_diff_width": "3.5",
```

However, this setting only accepts an integer (represented as a string for some reason) between 1 and 8. Your value is floored to 3.

![image](https://user-images.githubusercontent.com/2431823/93311232-083e1500-f806-11ea-8e17-bc1766a07ca1.png)

2020-09-16 10:12 UTC, dakshamdev commented
@rwols 
Thanks for Informing!
Issue Fixed 🙂

2020-09-30 14:33 UTC, FichteFoll requested changes

2020-09-30 14:33 UTC, FichteFoll commented on repository/d.json
> +					"tags": true
You changed the wrong `releases` array.

2020-10-03 06:42 UTC, closed without merging