added openssl configuration file syntax
wbond/package_control_channel pull request #8358
Opened 2021-09-05 06:30 UTC by finitelife

This package simply highlights the openssl configuration file syntax as it is slightly different from the INI syntax.
This includes default words, proper comment escaping, quoting, variable highlighting, section/name/value pair coloring, multiline values, directives, etc

2021-09-29 18:50 UTC, finitelife commented
"CI / trigger-review (pull_request) Failing after 3s — trigger-review"
Why is this happening? I'm not seeing any specific reason here vs any other accepted/closed pull requests.

2021-11-01 19:23 UTC, braver requested changes

2021-11-01 19:23 UTC, braver commented on repository/o.json
> +			"details": "https://github.com/finitelife/openssl-sublimetext",
The author and readme are just the defaults so we get those from the repo URL. So you can remove them here.

2021-11-01 19:30 UTC, braver commented
- author isn't actually an [allowed header key](https://www.sublimetext.com/docs/syntax.html) (put it in the readme or license)
- why does your package contains a sublime-color-scheme, and a settings file?
- a package-metadata.json has no place in a package

2021-11-20 12:24 UTC, closed without merging