Take over Squirrel
wbond/package_control_channel pull request #8418
Opened 2021-11-22 09:56 UTC by Enduriel

The [original author](https://github.com/iAmRoland/Sublime-Squirrel) of the squirrel plugin is unresponsive (hasn't replied to my email for months and 0 activity on any of their easily viewable social media for years). I've worked on significantly improving the package since I started working with Squirrel and think it should be used as the default for Package Control.

Hope I'm doing this right, used [this](https://github.com/wbond/package_control_channel/pull/5346) as a template.

2021-11-29 16:33 UTC, Ultra-Instinct-05 commented
@iAmRoland Are you okay with @Enduriel taking over the maintainer ship of the package ? If so, please respond within 14 days.

2021-11-29 17:08 UTC, iAmRoland commented
Sorry, was supposed to get back but completely forgot.

Yeah you can go ahead and transfer the maintainer ship. The changes in your branch seem pretty neat, if I ever use Squirrel again I'll try it out 😎

2021-11-30 20:25 UTC, braver commented
Thanks. 

Please don't ship color schemes with your syntax. There are hundreds of color schemes out there and people really want to use what they like. And people like to use their editor for loads of different languages. If you stick to the scope naming guidelines there is usually no need to tweak color schemes, and it allows color schemes author to effectively optimize for a wide range of languages.

2021-11-30 23:41 UTC, Enduriel commented
@iAmRoland awesome ty! I genuinely thought something had happened to you since you were inactive on every social media you had linked so glad to hear you're okay.

@braver that is fair, in theory that should be the case, for the two specific themes I included it unfortunately was decidedly *not* so I bundled them together for the people I was sharing it with but I'll move it to a different repo.

2021-11-30 23:48 UTC, Enduriel commented
Done

2021-12-02 03:52 UTC, Ultra-Instinct-05 commented
I forgot to mention another thing. Since your package is using the `.sublime-syntax` format, you need to specify `"sublime_text": ">=3092"` since the format was introduced in that build. To continue for any ST2 users (for whatever goddamn reason), you can do something like this.

```json
"releases": [
    {
        "base": "https://github.com/iAmRoland/Sublime-Squirrel",
        "sublime_text": "<3092",
        "branch": "master"
    },
    {
        "sublime_text": ">=3092",
        "tags": true
    }
]
```

2021-12-02 10:06 UTC, jrappen commented
Also, please add a license.

2021-12-02 14:12 UTC, Enduriel commented
@Ultra-Instinct-05 done and @jrappen done.

Also I would argue if someone is still using ST2 they deserve anything that happens to them :P

2021-12-02 16:47 UTC, braver requested changes

2021-12-02 16:47 UTC, braver commented on repository/s.json
> +					"branch": "master"
Actually, ST < 3092 is not supported either, there is no need to take those versions into account here. Especially not via branch based releases.

2021-12-02 16:48 UTC, braver commented
@Ultra-Instinct-05 is strictly correct, but we don't enforce support for < 3092. "ST3 support" is assumed to mean versions newer than that.

2021-12-02 16:56 UTC, jrappen commented
If you ask me, you're wasting your time with ST3 support. I believe the vast majority has already moved on.

I'd target `>=4107` (first public stable ST4 Build).

2021-12-02 17:00 UTC, braver commented
Honestly, after a package is submitted nobody verifies the compatibility anymore. Make life easy for yourself and just support whatever you’re using yourself. Nobody using an ancient unsupported version of Sublime Text is looking for new packages.

> Op 2 dec. 2021 om 17:56 heeft Johannes Rappen ***@***.***> het volgende geschreven:
> 
> ﻿
> If you ask me, you're wasting your time with ST3 support. I believe the vast majority has already moved on.
> 
> I'd target >=4107 (first public stable ST4 Build).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-02 17:11 UTC, Enduriel commented
I think from what I understand the thing I'd most prefer to go with would be @jrappen's suggestion, as if I use features that have been added later than that (which I might end up doing at some point but it'd definitely be a conscious decision) I can cap the release for those versions to a specific tag from what I understand?

And like I don't know, someone might have a rando reason to not use the latest latest version of ST4 which in my opinion is fair enough. If they're using ST4 it will be fine (the sublime-syntax file was first done for my own personal stuff before ST4 even released).

Is that alright?

2021-12-04 21:24 UTC, braver commented
I would say just drop the release for < 4107 and if someone has some random reason to use an outdated version of ST you can tell in them (in the readme) how to manually install a specific version of your package. You don't need to do everything via package control, just make life easy for yourself.

2021-12-04 21:51 UTC, Enduriel commented
@braver I mean it doesn't cost me anything to point older versions to the other repo just in case, not sure why not to do that?

2021-12-04 21:55 UTC, braver commented
Sure, whatever you like. I just want to get rid branch thing.

2022-01-10 19:28 UTC, braver commented
Please respond to the feedback to continue this PR.

2022-01-26 11:10 UTC, Enduriel commented
Sorry for taking so long, @braver I've removed the section like you asked.

2022-01-26 13:11 UTC, merged