Add JunLang
wbond/package_control_channel pull request #8855
Opened 2023-12-14 09:59 UTC by lemonorangeapple

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is `JunLang`

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

2023-12-14 10:00 UTC, lemonorangeapple commented
@packagecontrol-bot .

2023-12-16 09:30 UTC, braver requested changes

2023-12-16 09:30 UTC, braver commented on channel.json
> +		"https://raw.githubusercontent.com/Jun-Software/JunLang_package/package/package.json",
Please remove this line, it's not needed. Just your repo listed in j.json is enough.

2023-12-16 09:30 UTC, braver commented on repository/j.json
> +			"labels": ["JunLang"],
```suggestion
			"labels": ["JunLang", "language syntax"],
```

2023-12-16 09:31 UTC, braver commented
Please have a look the [scope naming guide](https://www.sublimetext.com/docs/scope_naming.html) and ensure your scopes all end with `.junlang`.

2023-12-17 08:48 UTC, lemonorangeapple commented
@braver I changed them. Can it work now?

2023-12-18 15:49 UTC, braver commented
That's better :) Please do add a README, otherwise people won't really understand what your package is about. For instance, link to information about the language your package supports. 

Also please don't forget to tag a new release with your improvements, package control only sees your tags: other changes are just sitting there in your repo and won't make it to end users. 

Let's not let that stop us from shipping this. Just do those things in your own time.

2023-12-18 15:49 UTC, merged