Candy Dark Color Scheme
wbond/package_control_channel pull request #8914
Opened 2024-04-30 17:33 UTC by rahulsharmagg

Added Candy Dark Color Scheme

- [✔] I'm the package's author and/or maintainer.
- [✔] I have have read [the docs][1].
- [✔] I have tagged a release with a [semver][2] version number.
- [✔] My package repo has a description and a README describing what it's for and how to use it.
- [✔] My package doesn't add context menu entries. *
- [✔] My package doesn't add key bindings. **

My package is Candy-Dark Color Scheme
There are no packages like it in Package Control.
![150641656-374ea307-409e-4d73-b864-52791d007765](https://github.com/wbond/package_control_channel/assets/36887105/c7fc045e-24c5-4fa0-8138-39025aedde9f)

2024-04-30 17:39 UTC, rahulsharmagg commented
### Candy Dark Color Scheme
Added Vibrant Colourful Color Scheme "**Candy Dark**" **SPECIALLY** for
JavaScript + CSS + HTML &
-  Regex
- PHP 
- OTHER LANG (BASIC)

2024-05-01 07:30 UTC, rahulsharmagg commented
**### Candy Dark Color Scheme**
Added Vibrant Colourful Color Scheme "**Candy Dark**" SPECIALLY for
JavaScript + CSS + HTML &

- > Regex
- > PHP
- > OTHER LANG (BASIC)

2024-05-14 19:50 UTC, braver requested changes

2024-05-14 19:50 UTC, braver commented on repository/c.json
> +			"releases": [
```suggestion
			"labels": ["color scheme"],
			"releases": [
```

2024-05-14 19:51 UTC, braver commented
Please ensure your package is added in alphabetical order.

2024-05-16 06:59 UTC, rahulsharmagg commented
I updated the code as needed.

2024-05-16 07:25 UTC, merged