Update g.json
wbond/package_control_channel pull request #8929
Opened 2024-06-03 18:43 UTC by ZainIftikhar7vals

- [ ] I'm the package's author and/or maintainer.
- [ ] I have have read [the docs][1].
- [ ] I have tagged a release with a [semver][2] version number.
- [ ] My package repo has a description and a README describing what it's for and how to use it.
- [ ] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

My package is similar to ... However it should still be added because ...

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

2024-06-17 20:43 UTC, kaste commented
This looks good to me but I do wonder

```
      gem_home = os.popen("echo $GEM_HOME").read().split("\n")[0]
      gems_directories = [
        os.path.expanduser("%s/gems/" % gem_home),
        os.path.expanduser("%s/bundler/gems/" % gem_home)
      ]
```

Isn't that readable just from within Sublime Text using `os.environ["GEM_HOME"]`.  Would be nice to make it available for Windows too.  Is that impossible to achieve?

The latest tag right now is "0.2.0-alpha".  Not sure if a suffix (`-alpha`) counts as release version.  braver will know that, or change it to just `0.3.0`.

2024-06-18 07:37 UTC, kaste commented
* Please lift the plugin to run on the 3.8 host. For that, create a file .python-version with its only contents 3.8\n in the root of your package.

2024-06-19 16:34 UTC, ZainIftikhar7vals commented
> * Please lift the plugin to run on the 3.8 host. For that, create a file .python-version with its only contents 3.8\n in the root of your package.

Can you please explain it a little bit more, as I am new to Sublime package development?

2024-06-19 16:36 UTC, ZainIftikhar7vals commented
> Would be nice to make it available for Windows too. Is that impossible to achieve?

It's definitely possible, but since I don't have access to a Windows machine right now, I can't test it. However, I plan to do so in the future.

2024-06-19 19:06 UTC, kaste commented
Yeah, to "lift" the package (or better worded: choose the environment) create a file just like https://github.com/kaste/InlineOutline/blob/master/.python-version.

2024-06-20 07:31 UTC, ZainIftikhar7vals commented
@kaste All comments resolved.

2024-06-20 08:20 UTC, kaste commented
We need @braver for the merge.

2024-06-20 08:26 UTC, koen-at-peppered requested changes
Just some final tweaks to the entry here, looks good otherwise 👍

2024-06-20 08:26 UTC, koen-at-peppered commented on repository/g.json
> +			"readme": "https://raw.githubusercontent.com/ZainIftikhar7vals/GotoRubyGem/main/README.md",
Your readme is in the default location so no need to reference it here.
```suggestion
```

2024-06-20 08:26 UTC, koen-at-peppered commented on repository/g.json
> +			"labels": ["code navigation", "ruby gems"],
```suggestion
			"labels": ["code navigation", "ruby gems", "ruby"],
```
A general "ruby" label will be more useful actually.

2024-06-20 11:19 UTC, ZainIftikhar7vals commented
@koen-at-peppered changes have been incorporated, please review.

2024-06-20 11:22 UTC, merged