feat: add templ
wbond/package_control_channel pull request #8955
Opened 2024-08-03 21:29 UTC by papierkorp

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

2024-08-21 07:56 UTC, braver commented
Looks like you reformatted the entire json file, please don't 😅 
The package itself looks good though.

2024-08-26 11:23 UTC, papierkorp commented
Sorry i havent noticed that I accidentally formatted the whole file >.<

2024-09-03 19:39 UTC, braver commented
Ah, that's better. Looks like the tests require indentation to be in tabs though.

2024-09-30 12:07 UTC, papierkorp commented
done :D

2024-11-07 19:39 UTC, braver requested changes

2024-11-07 19:39 UTC, braver commented on repository/t.json
> +			"description": "Syntax highlight for the go templ Plugin",
```suggestion
```

You don't need this line, Package Control will take the repo's description.

2024-11-13 09:57 UTC, braver approved these changes

2024-11-15 12:44 UTC, merged