eloquence syntax
wbond/package_control_channel pull request #8956
Opened 2024-08-06 16:39 UTC by macMikey

syntax for both eloquence program files and eloquence dialog files
https://eloquence.marxmeier.com/

2024-08-15 10:05 UTC, braver commented
Please use the checklist in the PR template to tell us about your package.

2024-08-15 13:24 UTC, macMikey commented
is this what you mean? i did not see the template, so i copied the template from another PR

* [x]  I'm the package's author and/or maintainer.
* [x]  I have have read [the docs](https://packagecontrol.io/docs/submitting_a_package).
* [x]  I have tagged a release with a [semver](https://semver.org) version number.
* [x]  My package repo has a description and a README describing what it's for and how to use it.
* [x]  My package doesn't add context menu entries. *
* [x]  My package doesn't add key bindings. **
* [x]  Any commands are available via the command palette.
* [x]  Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
* [x]  If my package is a syntax it doesn't also add a color scheme. ***
* [x]  If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
* [ ]  I use [.gitattributes](https://www.git-scm.com/docs/gitattributes#_export_ignore) to exclude files from the package: images, test files, sublime-project/workspace.


there are no extraneous files or directories in the repo, so, there is no need for .gitattributes

2024-08-21 07:57 UTC, braver commented
Was this intended to be a syntax file too? https://github.com/macMikey/eloquence-sublime-text-syntax/blob/main/dlg-sublime-syntax.yaml

2024-08-21 08:01 UTC, braver commented
In captures, you don't need to put quotes around the indexes. Also please ensure all scopes end with `.eq` (matching "source`.eq`"). Also please double check [the guidelines](https://www.sublimetext.com/docs/scope_naming.html), you might be able to specify some of those keywords. E.g.:

```yml
captures:
        1: keyword.control.eq
        2: entity.name.function.eq
```

2024-08-21 08:02 UTC, braver requested changes

2024-08-21 08:02 UTC, braver commented on repository/e.json
> +			"name": "Eloquence Syntax",
> If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").

.... 🧐 


```suggestion
			"name": "Eloquence",
```

2024-08-21 14:42 UTC, macMikey commented
> Was this intended to be a syntax file too? https://github.com/macMikey/eloquence-sublime-text-syntax/blob/main/dlg-sublime-syntax.yaml

there are two types of eloquence files: eloquence program files (.eq), and eloquence dialog files (.dlg). they are supposed to be included.

2024-08-21 15:00 UTC, macMikey commented
thanks for your patience, i'm a package n00b

2024-08-21 15:04 UTC, braver commented
You'll probably want to rename [dlg-sublime-syntax.yaml](https://github.com/macMikey/eloquence-sublime-text-syntax/blob/main/dlg-sublime-syntax.yaml) to `dlg.sublime-syntax` then. 

> thanks for your patience, i'm a package n00b

No worries, that's what we're here for 😉

2024-08-21 17:27 UTC, macMikey commented
> You'll probably want to rename [dlg-sublime-syntax.yaml](https://github.com/macMikey/eloquence-sublime-text-syntax/blob/main/dlg-sublime-syntax.yaml) to `dlg.sublime-syntax` then.
> 
> > thanks for your patience, i'm a package n00b
> 
> No worries, that's what we're here for 😉

done

2024-08-21 17:58 UTC, braver commented
Alright, main thing then remains that all scopes need to end with the identifier of the syntax, ie. `keyword.dlg` and `keyword.eq`, etc. This makes it possible for package developers to target your specific syntax.

2024-08-22 15:49 UTC, macMikey commented
so: in the .dlg syntax file, all of the scopes end in .dlg and in the .eq file, all the scopes end in .eq?

2024-08-22 15:52 UTC, braver commented
Yes. Basically your base scope for a syntax is source.XX and then you make sure all the scopes in that syntax also end with .XX

2024-08-22 18:52 UTC, braver commented
Almost!

source.dlg.eq should still be source.dlg

Also remember that your captures also assign scopes, so you need to cover those as well.

Have a look at some example syntaxes like https://github.com/sublimehq/Packages/blob/master/CSS/CSS.sublime-syntax#L3216C1-L3224C43

2024-08-22 21:43 UTC, macMikey commented
* source.dlg updated
* captures updated

thanks for all the help.

2024-08-23 06:48 UTC, braver commented
Looks good!

2024-08-23 06:48 UTC, merged

2024-08-23 14:43 UTC, macMikey commented
thanks for all the help.
package-control n00b...out

2024-08-23 15:03 UTC, braver commented
🫡