TokensCounter package added
wbond/package_control_channel pull request #8985
Opened 2024-10-03 22:47 UTC by yaroslavyaroslav

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is simply counting selected line as token, which is useful for folks that are working with llm. Is uses phantoms to present the calculations.

There's no package alike that, because there were lack of dependencies to perform this operation. Now they are available in PC.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

2024-10-03 22:52 UTC, yaroslavyaroslav commented
Looks like tests failing not by my fault.

2024-10-05 19:34 UTC, braver requested changes
Took me a while to realize what kind of tokens 😅 Package looks good though. Just one minor remark about your entry here.

2024-10-05 19:34 UTC, braver commented on repository/t.json
> +			"issues": "https://github.com/yaroslavyaroslav/SublimeTokenCounter/issues",
That's the default URL for issues so no need to add it here, PackageControl will find that automatically.

```suggestion
```

2024-10-08 21:01 UTC, yaroslavyaroslav commented
@braver could you please check it once again, as I applied fixes that have been requested.

2024-10-09 11:36 UTC, merged