Added VHS syntax package
wbond/package_control_channel pull request #8997
Opened 2024-11-03 07:01 UTC by patopesto

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a syntax highlighter for charmbracelet's [VHS](https://github.com/charmbracelet/vhs) tape files

There are no packages like it in Package Control.

2024-11-03 07:06 UTC, patopesto commented
The repository actually contains a top level LICENSE file. Not entirely sure how to handle the bot's warning

2024-11-04 18:28 UTC, braver commented
That's a bit of a weird test result. Maybe the script just got confused, because your repo does seem to be missing a syntax file? 🧐

2024-11-05 02:12 UTC, patopesto commented
Oops terribly sorry. I've now committed the forgotten syntax file.

2024-11-05 10:05 UTC, braver commented
Not sure what the bot is on about… anyway

- Your variable.annotation scope is missing the tape suffix
- Perhaps you could specify those keywords a bit?
- In your PR here you don’t have to specify the author, it will pick up your GitHub username automatically

2024-11-09 17:30 UTC, patopesto commented
Thanks for the feedback. 
I updated the missing suffix and the tag.
However I'm not sure I totally understand what you mean by "specifying the keywords a bit". The language is very simple and only contains a specific set of commands/keywords which are parsed. Are you suggesting parsing each individual commands?

2024-11-09 18:07 UTC, braver commented
> The language is very simple and only contains a specific set of commands/keywords which are parsed

It seemed like you have two sets of keywords, keys and instructions and they might map to one of the [common groups of keywords](https://www.sublimetext.com/docs/scope_naming.html#keyword).. or not, also fine 🙂 

In any case something you can refine later.

2024-11-09 18:08 UTC, braver requested changes

2024-11-09 18:08 UTC, braver commented on repository/v.json
> +			"author": "patopesto",
Since this is just your GitHub username you can omit it. 

```suggestion
```

2024-11-10 09:41 UTC, braver approved these changes

2024-11-10 09:42 UTC, merged