Package added: BBC BASIC Modern Syntax
wbond/package_control_channel pull request #9026
Opened 2024-12-30 16:31 UTC by sarev

- [y] I'm the package's author and/or maintainer.
- [y] I have have read [the docs][1].
- [y] I have tagged a release with a [semver][2] version number.
- [n] My package repo has a description and a README describing what it's for and how to use it.
- [y] My package doesn't add context menu entries. *
- [y] My package doesn't add key bindings. **
- [n/a] Any commands are available via the command palette.
- [n/a] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [y] If my package is a syntax it doesn't also add a color scheme. ***
- [y&n] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [n/a] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is BBC BASIC Modern Syntax. 

This is a more comprehensive version of the BBC BASIC language syntax than the pre-existing "BBC BASIC Syntax" package. This language syntax is more targeted at source code developed on or for RISC OS (the native home of BBC BASIC) and supports expressions and inline assembler (for example).

The pre-existing "BBC BASIC Syntax" package provides a simplified/generic syntax so as to support various ports of BBC BASIC (e.g. BBC BASIC for Windows, Brandy, etc.).

2025-01-26 16:05 UTC, braver requested changes

2025-01-26 16:05 UTC, braver commented on repository/b.json
> +			"name": "BBC BASIC Modern Syntax",
As for the package itself:

- You should not have a package-metadata.json file, the package metadata, as far as any is needed, is managed by package control via your entry here.
- A license file typically goes in the root directory. In fact, the subdirectory serves very little purpose here. 
- The [name](https://github.com/sarev/BBC-BASIC-Sublime-Syntax/blob/main/BBCBASICModernSyntax/BBCBASICModernSyntax.sublime-syntax#L10) should be the name of the language. So probably BBC BASIC, and definitely without the "Syntax" suffix.
- All scopes in your syntax must end with `.bbcbasic` to allow other packages to target them specifically.
- Please have a look at the [Scope Naming guide](https://www.sublimetext.com/docs/scope_naming.html). For instance, instead of specifying  your keywords in comments (`keyword  # The control statement (ELSE, OTHERWISE, etc.)` use `keyword.control`. This adds detail to your syntax, allows for more consistent highlighting, and might enable various other features in Sublime.
- `name` is not a commonly used scope name, perhaps `entity.name` might apply here instead?

2025-01-29 17:32 UTC, sarev commented on repository/b.json
> +			"name": "BBC BASIC Modern Syntax",
Many thanks for the constructive feedback. Sorry for the noob errors! Will look into all this...

2025-03-15 17:01 UTC, braver commented
@sarev let us know when you've had a chance to handle the feedback.

2025-03-31 14:55 UTC, closed without merging