Update Nunjucks Releases to Fix Syntax Loading Error
wbond/package_control_channel pull request #9027
Opened 2024-12-31 14:32 UTC by alsolovyev

### Changes:
- update the `releases` field to include version-specific details

### Notes:
Please confirm if I’ve configured everything correctly: all new releases are for version >4188, while tags: "2.0.1" remains for <=4188. This is necessary to resolve the [error](https://github.com/alsolovyev/Nunjucks/issues/27):

> Error loading syntax file "Packages/Nunjucks/Syntaxes/Nunjucks.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit.

### Details:

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [ ] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

2025-01-01 15:21 UTC, braver requested changes

2025-01-01 15:21 UTC, braver commented on repository/n.json
> +					"tags": "2.0.1"
I believe valid values for "tags" is either `true` or a prefix string, ie. not specific versions. The typical way to handle this situation is to tag ref `2.0.1` also with, e.g. `st3-2.0.1`, and then to specify `st3-` here. This allows you to create new tags to fix issues in that branch of your project, without having to open new PR's. 
See also https://raw.githubusercontent.com/wbond/package_control/master/example-repository.json and search for `The "tags" key`.

2025-01-01 22:11 UTC, alsolovyev commented on repository/n.json
> +					"tags": "2.0.1"
thank you for the fast response and detailed explanation! I appreciate your guidance.

I’ve updated the tags as per your suggestion - please check the new version. Additionally, I wanted to ask: is it possible to rename the 2.0.2 tag to st3-2.0.2, or should i create a new one with the correct name?

2025-01-03 13:05 UTC, braver commented on repository/n.json
> +					"tags": "2.0.1"
> I’ve updated the tags as per your suggestion - please check the new version

Looks good 👍🏻 

> is it possible to rename the 2.0.2 tag to st3-2.0.2, or should i create a new one with the correct name?

Renaming doesn't really exist in git. But you can add as many new tags to any version as you like, and you can remove those you don't need anymore.

One thing to think about though is that Package Control will already have seen your 2.0.3 tag, and will have delivered to users already (assuming most of them have used ST in the days since that tag was created). And it will not actually go and deliver versions with a lower number to any of those users. So, even once we merge this PR, versions < 2.0.3, prefixed or not, will probably not go anywhere. I'm not 100% on this and how this works out in practice.. but I would advise to make sure that the version you want to have delivered to st3 users is tagged with a high enough number so that it's going to get rolled out to all users. Just think of the prefixed versions as a "branch" of releases for your package: 2.0.2 without the prefix does not need to be the same as 2.0.2 _with_ the prefix.

2025-01-03 14:16 UTC, merged